name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          GH_CLI_VERSION=2.45.0
          curl -sSL "https://github.com/cli/cli/releases/download/v${GH_CLI_VERSION}/gh_${GH_CLI_VERSION}_linux_amd64.tar.gz" -o gh.tar.gz
          tar -xzf gh.tar.gz
          sudo mv gh_${GH_CLI_VERSION}_linux_amd64/bin/gh /usr/local/bin/

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "${GITHUB_TOKEN}" | gh auth login --with-token

      - name: Create release
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --title="$tag" \
            --draft \
            --notes "" \
            ./main.js ./manifest.json
