name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: List files
        run: ls -al


      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

            gh release create "$tag" \
            --title="$tag" \
            --draft \
            --notes "" \
            ./main.js ./manifest.json

